// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package models

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type FieldStatus string

const (
	FieldStatusActive    FieldStatus = "active"
	FieldStatusSuspended FieldStatus = "suspended"
	FieldStatusInactive  FieldStatus = "inactive"
)

func (e *FieldStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FieldStatus(s)
	case string:
		*e = FieldStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FieldStatus: %T", src)
	}
	return nil
}

type NullFieldStatus struct {
	FieldStatus FieldStatus
	Valid       bool // Valid is true if FieldStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFieldStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FieldStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FieldStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFieldStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FieldStatus), nil
}

type FieldTypes string

const (
	FieldTypesGH    FieldTypes = "GH"
	FieldTypesBlock FieldTypes = "Block"
)

func (e *FieldTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FieldTypes(s)
	case string:
		*e = FieldTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for FieldTypes: %T", src)
	}
	return nil
}

type NullFieldTypes struct {
	FieldTypes FieldTypes
	Valid      bool // Valid is true if FieldTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFieldTypes) Scan(value interface{}) error {
	if value == nil {
		ns.FieldTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FieldTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFieldTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FieldTypes), nil
}

type PilotClassifications string

const (
	PilotClassificationsA PilotClassifications = "A"
	PilotClassificationsB PilotClassifications = "B"
	PilotClassificationsC PilotClassifications = "C"
	PilotClassificationsD PilotClassifications = "D"
)

func (e *PilotClassifications) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PilotClassifications(s)
	case string:
		*e = PilotClassifications(s)
	default:
		return fmt.Errorf("unsupported scan type for PilotClassifications: %T", src)
	}
	return nil
}

type NullPilotClassifications struct {
	PilotClassifications PilotClassifications
	Valid                bool // Valid is true if PilotClassifications is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPilotClassifications) Scan(value interface{}) error {
	if value == nil {
		ns.PilotClassifications, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PilotClassifications.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPilotClassifications) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PilotClassifications), nil
}

type PilotStatuses string

const (
	PilotStatusesActive    PilotStatuses = "active"
	PilotStatusesInactive  PilotStatuses = "inactive"
	PilotStatusesSuspended PilotStatuses = "suspended"
)

func (e *PilotStatuses) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PilotStatuses(s)
	case string:
		*e = PilotStatuses(s)
	default:
		return fmt.Errorf("unsupported scan type for PilotStatuses: %T", src)
	}
	return nil
}

type NullPilotStatuses struct {
	PilotStatuses PilotStatuses
	Valid         bool // Valid is true if PilotStatuses is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPilotStatuses) Scan(value interface{}) error {
	if value == nil {
		ns.PilotStatuses, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PilotStatuses.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPilotStatuses) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PilotStatuses), nil
}

type UserAccess string

const (
	UserAccessSuperadmin UserAccess = "superadmin"
	UserAccessAdmin      UserAccess = "admin"
	UserAccessUser       UserAccess = "user"
)

func (e *UserAccess) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserAccess(s)
	case string:
		*e = UserAccess(s)
	default:
		return fmt.Errorf("unsupported scan type for UserAccess: %T", src)
	}
	return nil
}

type NullUserAccess struct {
	UserAccess UserAccess
	Valid      bool // Valid is true if UserAccess is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserAccess) Scan(value interface{}) error {
	if value == nil {
		ns.UserAccess, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserAccess.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserAccess) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserAccess), nil
}

type VarietyTypes string

const (
	VarietyTypesContinuous VarietyTypes = "continuous"
	VarietyTypesCyclic     VarietyTypes = "cyclic"
)

func (e *VarietyTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VarietyTypes(s)
	case string:
		*e = VarietyTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for VarietyTypes: %T", src)
	}
	return nil
}

type NullVarietyTypes struct {
	VarietyTypes VarietyTypes
	Valid        bool // Valid is true if VarietyTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVarietyTypes) Scan(value interface{}) error {
	if value == nil {
		ns.VarietyTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VarietyTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVarietyTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VarietyTypes), nil
}

type Farm struct {
	ID               int64
	FarmCode         string
	FarmPolygon      string
	FarmAirspace     string
	FarmLocation     string
	FarmCreationDate time.Time
	FarmContact      int64
}

type Field struct {
	ID                sql.NullInt64
	FieldName         string
	FieldType         FieldTypes
	FieldFarmID       string
	FieldVarietyID    string
	FieldPolygon      string
	FieldArea         string
	FieldDieback      string
	FieldStageName    string
	FieldStatus       FieldStatus
	FieldNotes        string
	FieldCreationDate time.Time
}

type Flight struct {
	ID             int64
	FlightDate     time.Time
	FlightFarmID   string
	FlightDuration string
	FlightPilot    string
	FlightAcreage  string
}

type Operator struct {
	ID                           int64
	OperatorID                   string
	OperatorName                 string
	OperatorHeadquater           string
	OperatorNumberPilotsDeployed int32
	OpertorContact               int64
}

type Pilot struct {
	ID                    int64
	PilotID               string
	PilotOperatorID       string
	PilotInitials         string
	PilotNumber           int32
	PilotFullName         string
	PilotEntryDate        time.Time
	PilotLicenseNumber    int64
	PilotFarmLocationCode string
	PilotFarmLocation     string
	PilotStatus           PilotStatuses
	PilotClassification   PilotClassifications
	PilotFlightHours      string
	PilotCoveredAcreage   string
}

type User struct {
	ID               int64
	Username         string
	Email            string
	Password         string
	UserCreationDate time.Time
	Access           UserAccess
}

type Variety struct {
	ID                      int64
	VarietyInternalIdentity string
	VarietyBotanicalName    string
	VarietyFarmID           string
	VarietyCreationDate     time.Time
	VarietyAcreage          int64
	VarietyType             VarietyTypes
	// 7 day encoding e.g 1010000 for sunday and tuesday schedule
	VarietyItervalCode string
}
